# Generated by Django 3.1.5 on 2021-01-27 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdd_Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=5, upload_to='')),
                ('price', models.IntegerField()),
                ('lot', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('engine', models.IntegerField()),
                ('milage', models.CharField(max_length=255)),
                ('kilometers', models.IntegerField()),
                ('home_delivery', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=6)),
                ('delivery_area', models.CharField(max_length=255)),
                ('warrenty', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=6)),
                ('warrenty_period', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
