# Generated by Django 3.1.5 on 2021-01-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0002_auto_20210128_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_car',
        ),
        migrations.RemoveField(
            model_name='postadd_car',
            name='image',
        ),
        migrations.AddField(
            model_name='postadd_car',
            name='image',
            field=models.ManyToManyField(related_name='image', to='post_add.Image'),
        ),
    ]
