# Generated by Django 3.1.5 on 2021-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0003_auto_20210128_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadd_car',
            name='image',
        ),
        migrations.AddField(
            model_name='postadd_car',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='postadd_car',
            name='warrenty_period',
            field=models.IntegerField(default='SOME STRING'),
        ),
    ]
