# Generated by Django 3.1.5 on 2021-01-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0006_remove_postadd_car_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadd_car',
            name='image',
        ),
    ]
