# Generated by Django 3.1.5 on 2021-01-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0009_remove_postadd_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_car',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
