# Generated by Django 3.1.5 on 2021-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0011_auto_20210131_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_car',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
