# Generated by Django 3.1.5 on 2021-01-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0012_auto_20210131_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_car',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
