# Generated by Django 3.1.5 on 2021-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0013_postadd_car_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
