# Generated by Django 3.1.5 on 2021-01-31 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_add', '0014_auto_20210131_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_car',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
