# Generated by Django 3.1.5 on 2021-02-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0016_auto_20210131_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadd_car',
            name='username',
        ),
    ]
