# Generated by Django 3.1.5 on 2021-02-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0018_postadd_car_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadd_car',
            name='username',
        ),
    ]
