# Generated by Django 3.1.5 on 2021-02-01 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_add', '0024_auto_20210201_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_car',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='postadd_car',
            name='username',
            field=models.ForeignKey(default='akdkl', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
