# Generated by Django 3.1.5 on 2021-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0026_auto_20210201_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadd_car',
            name='username_id',
        ),
        migrations.AddField(
            model_name='postadd_car',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
