# Generated by Django 3.1.5 on 2021-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0028_auto_20210201_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_car',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
