# Generated by Django 3.1.5 on 2021-02-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0031_auto_20210201_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_car',
            name='username',
            field=models.CharField(blank=True, default='dsfsdfdsfds', max_length=255, null=True),
        ),
    ]
