# Generated by Django 3.1.5 on 2021-02-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0032_auto_20210201_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
