# Generated by Django 3.1.5 on 2021-02-05 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0033_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_car',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
