# Generated by Django 3.1.5 on 2021-02-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0036_postadd_bikes_postadd_computer_postadd_fashion_postadd_landhouse_postadd_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_bikes',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_car',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_computer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_fashion',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_landhouse',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_phones',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
