# Generated by Django 3.1.5 on 2021-02-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0037_auto_20210209_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_landhouse',
            name='bedroom',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
