# Generated by Django 3.1.5 on 2021-02-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0038_postadd_landhouse_bedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_bikes',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='postadd_bikes',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_bikes',
            name='usedFor',
            field=models.DateField(blank=True, default=''),
        ),
    ]
