# Generated by Django 3.1.5 on 2021-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0039_auto_20210211_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_bikes',
            name='usedFor',
            field=models.DateField(blank=True, default='2020-2-2'),
        ),
    ]
