# Generated by Django 3.1.6 on 2021-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0044_auto_20210211_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_car',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
