# Generated by Django 3.1.6 on 2021-02-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0045_postadd_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdvertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add1', models.ImageField(default='', upload_to='')),
                ('Add2', models.ImageField(default='', upload_to='')),
                ('Add3', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
