# Generated by Django 3.1.6 on 2021-02-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0046_postadvertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd_bikes',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_car',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_computer',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_fashion',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_landhouse',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postadd_phones',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
