# Generated by Django 3.1.6 on 2021-02-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0047_auto_20210215_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_bikes',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_car',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_computer',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_fashion',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_landhouse',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_phones',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
