# Generated by Django 3.1.6 on 2021-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0048_auto_20210215_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postadd_computer',
            old_name='professor',
            new_name='processor',
        ),
        migrations.AlterField(
            model_name='postadd_bikes',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_bikes',
            name='type',
            field=models.CharField(blank=True, choices=[('Scooter', 'Scooter'), ('Bikes', 'Bikes')], max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_computer',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_fashion',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_fashion',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_fashion',
            name='type',
            field=models.CharField(blank=True, choices=[('T-Shirt', 'T-Shirt'), ('Polo', 'Polo'), ('Shirt', 'Shirt'), ('Jeans', 'Jeans'), ('Trouser & Shorts', 'Trouser & Shorts'), ('Tops', 'Tops'), ('Kurtha', 'Kurtha'), ('Saries', 'Saries'), ('Dress & Skirt', 'Dress & Skirt'), ('Coat & Suits', 'Coat & Suits'), ('Hoodie & Sweetshirt', 'Hoodie & Sweetshirt'), ('Sport & Gym', 'Sport & Gym'), ('Undergarments', 'Undergarments'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='postadd_phones',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
