# Generated by Django 3.1.7 on 2021-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_add', '0050_auto_20210217_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd_car',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
