# Generated by Django 3.1.5 on 2021-02-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20210207_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
