# Generated by Django 3.1.6 on 2021-02-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
