# Generated by Django 3.1.6 on 2021-02-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0011_auto_20210220_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
