# Generated by Django 3.1.6 on 2021-02-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0013_auto_20210220_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
