# Generated by Django 3.1.6 on 2021-02-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0016_auto_20210220_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password2',
            field=models.CharField(max_length=255),
        ),
    ]
