# Generated by Django 3.1.6 on 2021-02-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0018_userprofile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
