# Generated by Django 3.1.6 on 2021-02-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0019_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
    ]
