# Generated by Django 3.1.6 on 2021-02-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0020_auto_20210220_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
