# Generated by Django 3.1.6 on 2021-02-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0022_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
