# Generated by Django 3.1.6 on 2021-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0023_auto_20210221_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
