# Generated by Django 3.1.6 on 2021-02-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0031_auto_20210221_0812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
