# Generated by Django 3.1.6 on 2021-02-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0032_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
