# Generated by Django 3.1.6 on 2021-02-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0035_auto_20210221_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
