# Generated by Django 3.1.6 on 2021-02-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0037_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
