# Generated by Django 3.1.6 on 2021-02-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0038_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=255)),
                ('password2', models.CharField(default='', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
